# Generated by Django 3.1.5 on 2021-01-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_name', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Laptop', 'Laptop'), ('PC', 'PC'), ('Mobile', 'Mobile')], max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
