# Generated by Django 3.1.5 on 2021-01-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Delivered', 'Delivered'), ('Not Delivered', 'Not Delivered')], default='In Process', max_length=20),
        ),
    ]
