# Generated by Django 3.1.5 on 2021-01-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210122_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_name',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
