# Generated by Django 3.1.5 on 2021-01-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210128_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='longtitude',
        ),
    ]
