# Generated by Django 3.1.5 on 2021-01-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210128_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='type',
            field=models.CharField(choices=[('Phone number', 'Phone number'), ('Email', 'Email'), ('Physical address', 'Physical address')], default='Phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
