# Generated by Django 3.1.5 on 2021-02-12 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210208_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ыфду',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 2, 12)),
        ),
    ]
