# Generated by Django 3.1.5 on 2021-02-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210212_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='ыфду',
            new_name='sale',
        ),
    ]
