# Generated by Django 3.1.5 on 2021-02-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210212_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
